### ISSUE TITLE
Add Atom plugin

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#101]
Now that import-js has extracted the core into a standalone gem, it can be integrated more easily with additional editors. We already have emacs and Sublime Text support and we should add Atom support.

**Comment by lencioni** [comment]
This appears to be their official plugin tutorial: https://atom.io/docs/latest/hacking-atom-package-word-count

**Comment by lencioni** [comment]
Here's an Atom package that looks pretty simple and is not written in coffeescript (except for the tests), which might be helpful for learning how to do this: https://github.com/benjick/atom-elm-format

**Comment by lencioni** [comment]
It looks like Atom plugins are just npm packages, which is great. I think for this plugin, we should add an atom directory to the root of this project that will contain the package. I think we should probably name the package `atom-import-js`

**Comment by lencioni** [comment]
I started a branch for this at https://github.com/trotzig/import-js/tree/atom

I'm not sure when I'll have time to work on it next, so please feel free to pick it up and run with it.

**Comment by trotzig** [comment]
Nice!

**Comment by lencioni** [comment]
I made some good progress on the atom branch today, but have run out of time for now. Take a look or pick it up if you are interested.
