### ISSUE TITLE
Multi-line destructuring

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#106]
As lines get longer, it would probably make sense for destructuring to be broken out into one variable per line, such as seen in [the following code snippet](https://github.com/airbnb/enzyme/blob/9acb9d1414701374fd486bdf358ef5570dd78089/src/ShallowWrapper.js#L1-L24):

```js
import React from 'react';
import { flatten, unique, compact } from 'underscore';
import cheerio from 'cheerio';
import {
  nodeEqual,
  propFromEvent,
  withSetStateAllowed,
  propsOfNode,
} from './Utils';
import {
  debugNodes,
} from './Debug';
import {
  getTextFromNode,
  hasClassName,
  childrenOfNode,
  parentsOfNode,
  treeFilter,
  buildPredicate,
} from './ShallowTraversal';
import {
  createShallowRenderer,
  renderToStaticMarkup,
} from './react-compat';
```

**Comment by trotzig** [comment]
Sounds like a good improvement. What do you think should be the heuristic here? More than 2? Line longer than x chars?

Care to take this on? I'm not sure when I'll have time to look in to this.

**Comment by lencioni** [comment]
> What do you think should be the heuristic here? More than 2? Line longer than x chars?

I think we should use the max line length like we are using for wrapping near the `=`, but just use different wrapping mechanics for destructured import statements.

> Care to take this on?

Yep! I'll work on it today.

**Comment by trotzig** [comment]
awesome sauce! (bearnaise)

**Comment by lencioni** [comment]
I'm almost done, just working on some refactoring
