### ISSUE TITLE
Allow separate configuration for different directory trees

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#108]
If I am working on an app that uses JavaScript for the client side and Node.js for the server side, and I want to use ES2015 modules (ESM) import syntax on the client side, I am currently somewhat out of luck with import-js since Node.js doesn't yet support ESM and I don't really see it on their roadmap. For these cases, it would be nice if import-js had a way where I could use `const` for my server code and `import` for my client code.

One option would be to allow this to be configured in the `.importjs.json` file. Another option would be to allow `.importjs.json` files to be added wherever and then merged into the main configuration. I think this is the approach that ESLint takes, FWIW. 

I'm not really sure if the juice is worth the squeeze here, but I figured I'd open this issue while I was thinking about it.

**Comment by trotzig** [comment]
So, just to better understand your problem, you have this structure?
```
foo
  |- bar
  |- baz
  |- node_modules
```
where `foo` is the project root, `bar` is the client-side app, `baz` is the server-side Node app, and `node_modules` is where all node_modules go?

**Comment by lencioni** [comment]
Yes, more or less. There might be a few other directories in there that could be either server side or client side, but that is the gist of it.

**Comment by lencioni** [comment]
I'm working in a project where I normally want to remove `.jsx` extensions, except for a specific directory. This feature would come in useful for that as well.

**Comment by trotzig** [comment]
Is it specific to a `lookup_path`? I'm asking because we might get away with expanding the configuration or `lookup_paths`.

**Comment by lencioni** [comment]
This project is using relative paths for everything, so there isn't much meaningful `lookup_path` configuration yet. In this case, most JS is under `app/assets/javascripts`, and this directory happens to be under `app/assets/javascripts/something/somethingelse`.

**Comment by trotzig** [comment]
Ah, I see. Then the local .importjs.json makes sense.

**Comment by lencioni** [comment]
I am also finding myself wanting to import things in devDependencies in tests, so it would be nice to be able to switch that on for that directory. In the meantime, I can just add aliases.

**Comment by trotzig** [comment]
As far as I can remember, there's no option to turn on `devDependencies`. We currently grab `peerDependencies` along with `dependencies`.

**Comment by lencioni** [comment]
I was thinking about the pros and cons of adding local `.importjs.json` files vs adding configuration to one `.importjs.json` file, and I think there are merits to both. It might be worth considering supporting both, but for different reasons.

### Local `.importjs.json` files

- Pros: easy to understand, if directory moves then configuration moves with it
- Cons: possibly less discoverable, cannot apply to file patterns within a tree (e.g. if you want it to apply to `*-test.js` files within your tree

### Local config within an `.importjs.json` file

Pros: probably more discoverable, can be designed in a way to apply to file patterns within a tree
Cons: probably more difficult to understand, challenging to come up with clear naming of options

**Comment by trotzig** [comment]
Right now we have support for both of your suggestions (in the local-config branch). Thanks for continuing to come up with good ideas!

**Comment by lencioni** [comment]
I've given this a little more thought, and although having the separate `.importjs.json` file would work for my use-case, I think that putting the configuration all in one place is a better solution and I'm not sure we actually get much objective value out of supporting the separate file. And actually, having two ways to do this brings complexity and potentially confusion for consumers who are trying to reason about their configuration. It might be worth considering dropping that as an option. What do you think?

**Comment by trotzig** [comment]
Yeah, I had a plan to do so at the beginning of the day. Then it turned out
to be so easy to leave in. But yes, limiting the number of options is
probably a good tjing at this point.

**Comment by trotzig** [comment]
That code is now gone, so the only way to specify local configuration is through turning the config into an array and using `applies_to` and `applies_from`.

**Comment by trotzig** [comment]
I think this is essentially done. There might be some bugs to sort out before it's fully functional, but let's open new issues for that.
