### ISSUE TITLE
Fixing imports does not remove things from destructured imports

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#111]
If you have code and configuration that will result in fixing imports generating this:

```js
import Blah, {
  Bar,
  Baz,
  Bazz,
  Buzz,
  Fizz,
  Foo,
  Ooze,
  Poo,
} from 'something';
```

and then removing some or all of the references to variables that are imported and run fix imports again, all of them stay. This does not seem to be a problem with imports that are not destructured.

**Comment by lencioni** [comment]
I think I found the cause of this and #110. I just need to write a spec for it.

**Comment by trotzig** [comment]
cool
