### ISSUE TITLE
Auto-fix missing invisible React import when using JSX

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#113]
If you are using JSX, you need to import React even though the variable doesn't appear to be used. [eslint-plugin-react has a rule that detects this for you](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md), which we could piggyback off of.

This should probably be enabled (or disabled?) as an option, since some people might be defining `React` as a global variable.

**Comment by lencioni** [comment]
One bummer about this is that it would introduce a dependency on eslint-plugin-react.

**Comment by lencioni** [comment]
I guess the dependency wouldn't be too bad if this was off by default, and enabled as an option.

**Comment by trotzig** [comment]
Wouldn't it be enough to grep for "'React' must be in scope when using JSX (react/react-in-jsx-scope) [javascript/eslint]" or something? You're right in that it creates a dependency, but it's very soft. We don't even need a config option for that, we can just casually look for it. :)

**Comment by lencioni** [comment]
Yes I think so, but that would require that the eslint-plugin-react package is installed and the rule is enabled in the local `.eslintrc` file which seems probably okay but less than ideal--partly because it is different than what we do for the other two rules that we depend on for this functionality.
