### ISSUE TITLE
Prefer local eslint

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#115]
In #114 I improved some error reporting that happens when packages that are expected by the local project's `.eslintrc` file are not installed globally. It would be nice, however, if import-js preferred the locally installed eslint over the globally installed one, so it could just rely on these packages being installed locally.

Normally, to execute local node_modules binaries, I do something like ``$(npm bin)/executable`` since `npm bin` will output the path to the local `node_modules/.bin` directory.

**Comment by lencioni** [comment]
It needs to be more sophisticated than a simple

```diff
diff --git a/lib/import_js/importer.rb b/lib/import_js/importer.rb
index 6835299..8e6de17 100644
--- a/lib/import_js/importer.rb
+++ b/lib/import_js/importer.rb
@@ -97,6 +97,7 @@ module ImportJS
         --rule 'no-undef: 2'
         --rule 'no-unused-vars: [2, { "vars": "all", "args": "none" }]'
       ].join(' ')
+      command = "$(npm bin)/#{command} || #{command}"
       out, err = Open3.capture3(command,
                                 stdin_data: @editor.current_file_content)
```

because eslint will exit with an exit code of 1 if any errors are found while linting, which will cause the fallback eslint command to be run.

**Comment by trotzig** [comment]
Instead of doing this dynamically, I think it would make sense to bring back the config that allowed you to override it. I have a feeling that might be useful in other cases as well.

**Comment by lencioni** [comment]
Yeah, maybe it could just be a boolean for simpicity? Should it default to local or global installation?

**Comment by trotzig** [comment]
Default to global, but allow override to e.g. 'node_modules/.bin/eslint'. I think a boolean is too "handholdy", we might as well let people deal with it themselves.

**Comment by trotzig** [comment]
I think you are in a better situation to test this out. Would you mind taking it on?

**Comment by trotzig** [comment]
Actually, this should be rather simple. I can take it on later tonight as long as the stars align.

**Comment by lencioni** [comment]
I'll work on it now
