### ISSUE TITLE
Change default declaration keyword to import

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#118]
ES2015 modules (ESM) is the future and we can embrace this by changing the default declaration keyword from `var` to `import`. What do you say?

**Comment by trotzig** [comment]
Absolutely! We just have to make sure to mention it in the release notes. Also, this should be a semver minor version change, agree?

**Comment by lencioni** [comment]
Sure, why not?

**Comment by trotzig** [comment]
Alright, I'm about to take this on now. In celebration of your birthday so to speak. :)

**Comment by lencioni** [comment]
\o/
