### ISSUE TITLE
Use relative paths doesn't work when selecting from a list of multiple matches

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#123]

**Comment by lencioni** [comment]
Actually, relative paths might not be working for me at all in this project.

**Comment by trotzig** [comment]
Is this the same project that didn't have `lookup_paths`? I think we have something that checks if `import_path.start_with?(lookup_path)`, which won't work for paths starting with `.`. We should probably address that by stripping out any dots from the start of lookup paths. It's likely that someone will add e.g. `./app/assets` here too, which will suffer from the same problem.

**Comment by trotzig** [comment]
This was the line I was talking about: https://github.com/trotzig/import-js/commit/994f70d65d5bf001a3fa278083578634174745b0#diff-ca39607eaaa0631db83ec644bad6bab0R49

Though it was checking `make_relative_to` instead of `import_path`, but the result is the same.

**Comment by lencioni** [comment]
Yes, this is the same project that didn't have `lookup_paths`.
