### ISSUE TITLE
node_modules importing doesn't seem to be working as I expected

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#124]
I am working in a large project where I am trying to get import-js set up for the first time. In this project we have `moment` in our `package.json` file and I'd like to import it into a new module. However, when matching modules, import-js presents me with a list like the following:

```
ImportJS: Pick JS module to import for 'moment':
1: moment (main: ./moment.js)
2: node_modules/some-package/node_modules/convict/node_modules/moment (main: ./moment.js)
3: node_modules/some-package/node_modules/convict/node_modules/moment/moment
4: node_modules/some-package/node_modules/convict/node_modules/moment/package
5: node_modules/casual/node_modules/moment (main: ./moment.js)
6: node_modules/casual/node_modules/moment/moment
7: node_modules/casual/node_modules/moment/package
8: node_modules/moment (main: ./moment.js)
9: node_modules/moment/moment
10: node_modules/moment/package
```

Perhaps my memory is failing me, but I expected this to resolve to just one module, which happens to be the first on this list (see e237f86a).

**Comment by lencioni** [comment]
I'm not sure if this is related or not, but I have a module named `T` that I am importing and it seems to be matching on all sorts of deeply nested `toJSON` packages in the node_modules directory.

**Comment by lencioni** [comment]
Ah, I think that this and #123 might be because I hadn't set `lookup_paths` to anything. Once I added "app/assets/javascripts" to that, things worked more expectedly. This behavior seems a bit odd though, so perhaps there is something we can improve here?

**Comment by trotzig** [comment]
Ah, I see. I added that as a default so that at least you would get something to show up on importing. `node_modules` will be a problem however, so maybe we should just raise an exception when it hasn't been set? Even if we do that, we might want to deal with `node_modules` anyhow, because it's likely that `lookup_paths` will be `['.']`in some situations anyway.

**Comment by trotzig** [comment]
I think it would make sense to at least exclude `node_modules` dynamically if there is a `package.json` file.

**Comment by trotzig** [comment]
I looked into this briefly, and there is a simple fix we can do: dynamically adding `./node_modules` when you grab the `excludes` configuration. It will work, but it would be better to avoid dealing with node_modules at all when running the `find` command. Let me know what you think!

**Comment by lencioni** [comment]
It looks like we can exclude node_modules by using `-not -path "./node_modules/*"` with `find`.

**Comment by trotzig** [comment]
Good idea. I'm pushing a commit soon.
