### ISSUE TITLE
Path prefixes

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#125]
I am working in a project where there are a number of packages that are namespaced with the name of the organization (e.g. `organization-package-name`). However, the variables that are imported do not contain these namespaced versions (e.g. `PackageName`). This means that I have to add an alias for each package that is done this way.

I've only found about 9 so far, so it isn't a huge deal, but I don't like the added bookkeeping and I worry that the friction of maintaining this list as new packages are created will be frustrating. I am wondering if it would make sense to add an option that could be used to configure for this scenario. Perhaps a path prefix that it ignores when matching packages or something?

**Comment by trotzig** [comment]
I'm not sure what this means exactly. Could you provide a little more context? It's mostly the last sentence that confuses me:

> Perhaps a path prefix that it ignores when matching packages or something?

By "packages", do you mean something resolved from packages.json/node_modules?

**Comment by lencioni** [comment]
Yes, I'm referring to packages in the node_modules directory.

Think about this in the context of private npm packages. In this situation, you'd probably want to namespace all of your packages with your organization name to avoid collisions. However, when using the packages, you wouldn't want to import them with your organization name. For instance, if you were working at an organization called Brigade and had a private package that did dialogs, you might name the package `brigade-dialogs` but when you import it, you might want to import it as `Dialogs`.

```js
import Dialogs from 'brigade-dialogs';
```

Now, let's say you have a bunch of these types of packages and they all follow the pattern of:

```js
import MyPackage from 'brigade-my-package';
```

it would be nice to have a way to tell import-js that you use `brigade-` as a package prefix and to ignore it when trying to resolve `MyPackage` to its module.

Does that clarify things?

**Comment by trotzig** [comment]
Absolutely. That sounds reasonable. Any ideas for how to name that configuration option?

**Comment by lencioni** [comment]
Not sure. `ignorePackagePrefix` maybe?

**Comment by trotzig** [comment]
Sure. I guess it's most important that we have proper documentation for such a thing.

**Comment by lencioni** [comment]
This could also be useful for the `react-addons-*` packages, so maybe it should take an array or something like that?
