### ISSUE TITLE
Custom import syntax

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#130]
This is a bit complicated and very well might be outside of the scope of import-js.

I am working on a project that uses a custom function to import components in the JS specs. It uses regular `import` for other dependencies, such as npm packages. For the custom function, it does not use relative paths, and for the `import` statements it does. It looks something like this:

```js
import SomePackage from 'some-package';
import SomethingElse from 'something-else';
import Foo from '../foo';

const Bar = myCustomImporterThing('path/to/a/thing/bar');
const Baz = myCustomImporterThing('path/to/a/thing/baz');
```

I think that the custom importer applies to everything imported from a directory tree (e.g. `app/assets/javascripts/*`), but I could be wrong.

It would be nice if there was a way to configure or extend import-js to support this scenario.

**Comment by lencioni** [comment]
Also, I might have some of the details wrong here since I wasn't looking at the code when I wrote this up.

**Comment by lencioni** [comment]
I don't have a full solution in mind, but one strategy that comes to mind is looking for a `.importjs` directory in the project that contains ruby files that define classes that somehow provide extended functionality like this.

**Comment by lencioni** [comment]
If we go that route, it would be extra good if we abstracted it in a way that made the built-in import syntaxes implemented in the same way (but just pre-packaged).

**Comment by trotzig** [comment]
I think the `.importjs` solution is a bit heavy. It's quite complicated to understand, and is likely to lead to issues down the line because we can't control what code people are running for import-js. What if we instead did this:

- Introduce a configuration option that can be used to replace the `require` function. We can probably only support this when using `const`, `var` or `let`. 
- Allow local `.importjs.json` config files in the project. When looking up configuration, we'll look at the current file being imported (e.g. `app/assets/components/Foo.js`), start at project root and walk down the folder tree, merging any configuration we find (e.g. look for `app/.importjs.json`, `app/assets/.importjs.json`, `app/assets/components/.importjs.json`).

Those two changes combined could make the above scenario happen.

**Comment by lencioni** [comment]
I think this is close, but not quite. Since in this file there are actually two different types of imports happening, I think we would need to introduce a third change:

- Somewhat inversely to local `.importjs.json` files, allow configuration for modules that are matched within a subtree. i.e. if the `.import.json` file applies configuration to the source file that you are working in, there needs to be a way to apply configuration within that file to modules found in target trees. This would allow configuration for source files in `spec/*` to specify using `import` by default and then override that to use `const` for files in `app/*` and also change the `require` function for these things.

**Comment by trotzig** [comment]
I see. I'm starting to better understand your proposed solution now. But I wonder if we could solve it through configuration instead? I have a few ideas, but I'm not sure any of them would be good enough. 

We could allow the root configuration to specify path-local overrides, something like this:

```json
"local_configurations": [
  {
    "to": "app/assets/",
    "from": "*",
    "declaration_keyword": "import"
  },
  {
    "to": "app/assets/",
    "from": "spec/",
    "declaration_keyword": "const",
    "require_function": "myCustomImportFunc"
]
```

We could also allow local configurations to specify if they are `to` (applies when importing _to_ a file in a folder/subfolder), or `from` (applies when importing a file from the folder/subfolder). The default would be `to` (I think).

**Comment by lencioni** [comment]
I agree that we can probably solve this with configuration.

Instead of adding a `local_configurations` key that overrides the top-level configuration, what do you think about doing all configuration in this way? There's probably some overlap here with #108.

Although I like their shortness, by looking at the proposed configuration, I'm not sure I understand what `to` and `from` mean exactly (I'm not even sure I understand after after reading your description). We might want to work on those names a little more.

**Comment by trotzig** [comment]
So in this case we can't apply the configuration based on a local `.importjs.json` file. I think I'm going to apply something like this instead (basically what you suggested in #108): 

```json
"local_configs": [
  {
     "pattern": "app/components/**/*",
     "pattern_applies_to": "current_file",
     "config": {
       "declaration_keyword": "import"
    }
  },
  {
     "pattern": "spec/**/*",
     "patttern_applies_to": "file_being_imported",
     "config": {
       "declaration_keyword": "const",
       "import_function": "myCustomRequire"
    }
  },
  {
     "pattern": "**",
     "pattern_applies_to": "package_being_imported",
     "config": {
       "declaration_keyword": "const",
       "import_function": "myCustomRequire"
    }
  },
]
```

**Comment by trotzig** [comment]
This means that local configuration found in a local `.importjs.json` file will always apply to the file being edited.

**Comment by lencioni** [comment]
Is all of the nesting (`local_configs`, `config`) necessary? What if the config file was just an array at the top level instead of an object, and the `pattern` and `pattern_applies_to` keys were optional (defaulting to `*` or whatever). That way all configuration would be specified in exactly the same way.

Also, I don't think `pattern` and `pattern_applies_to` are any clearer than `from` and `to`.

**Comment by trotzig** [comment]
I actually decided to ditch the second config nesting.

Good idea about applying this pattern globally. We'll just have to make sure that you can still define an object directly. I'll sleep on it and pick it up after work tomorrow.

**Comment by trotzig** [comment]
@lencioni: Could you check out the latest changes from the local-config branch and give it a spin? I believe we're pretty close now. :smile:

**Comment by lencioni** [comment]
@trotzig I checked them out and they are working pretty well. However, I think the `applies_from` option needs to work with more of the other options. For instance, I have this configuration:

```json
 {
   "applies_to": "spec/javascripts/**",
   "applies_from": "app/assets/javascripts/**",
   "declaration_keyword": "const",
   "import_function": "mySpecialRequireFn",
   "use_relative_paths": false,
   "lookup_paths": [
     "app/assets/javascripts"
   ]
 }
```

And I was hoping it would generate a line like:

```js
const MyThing = mySpecialRequireFn('no/dots/in/this/path/to/MyThing');
```

But instead it gave me something like:

```js
const MyThing = mySpecialRequireFn('../../../app/assets/javascripts/no/dots/in/this/path/to/MyThing');
```

I noticed that this is explicitly mentioned in the readme, but unfortunately it doesn't fully work for my use-case.

One thing worth noting is that I happened to have multiple matches for the case I tried it on, so I was selecting this match from a list of possibilities in case that comes into play here.

**Comment by trotzig** [comment]
I'll look into it. I did this first pass with some rough assumptions.

**Comment by lencioni** [comment]
Thanks! Here's some more context that you might find helpful. In this particular project, half of the reason this custom import function is used is because the specs are so far away from the code they are testing, and the team wants to avoid having `../../../app/assets/javascripts` in every path in this case--thus needing to disable relative paths and adding a lookup path here.

**Comment by trotzig** [comment]
I wonder if the team would feel different after having a tool like import-js at their disposal? ;)

The lookup_paths is not going to work (it is used _before_ we know the path to the file being imported). I'm going to add a special configuration option that you can use to strip out things from the beginning of a path instead, perhaps `strip_from_path`?
