### ISSUE TITLE
Split out destructuring configuration from aliases

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#135]
Since adding destructuring to aliases configuration, the name `aliases` is overly specific. I think we should rename it to something that better captures how the configuration is actually used. `modules` comes to mind, but I'm open to other suggestions. And, when we make this change, I think we should make `path` optional. This would clear up some redundant configuration, like:

```json
"aliases": {
  "React": {
    "path": "react",
    "destructure": [
      "Children",
      "Component",
      "PropTypes"
    ]
  }
}
```

would then become:

```json
"modules": {
  "React": {
    "destructure": [
      "Children",
      "Component",
      "PropTypes"
    ]
  }
}
```

**Comment by trotzig** [comment]
I see your point, and when we added the destructure thing, the whole thing became something else. Though I worry that `modules` will make people think that they have to list all package dependencies here. I wonder if we instead should keep desctructure config outside of `aliases`. Something like this:

```json
"aliases": {
  "_": "underscore",
}, 
"package_destructures": {
  "react": [
    "Children",     
    "Component",
    "PropTypes"
  ],
  "underscore": [
    "omit",
    "memoize"
  ]
}
```

That way we don't have to add aliases just because we want to use destructuring.

**Comment by lencioni** [comment]
I think that sounds pretty good, but I have some questions.

- You can add destructuring for modules that are not packages, so does `package_destructures` make sense as a name? What about `destructure`?
- It looks like the key here is the path, is that correct? This is simple for packages, but what does it look like for modules that are not packages? i.e. do I need the full path? What if I am using relative paths, etc.?

**Comment by trotzig** [comment]
> You can add destructuring for modules that are not packages, so does package_destructures make sense as a name? What about destructure?

I guess that would be good. 

It looks like the key here is the path, is that correct? This is simple for packages, but what does it look like for modules that are not packages? i.e. do I need the full path? What if I am using relative paths, etc.?

Yes, that's what I thought. Not sure how to handle those to be honest. That's another issue that we have to solve, but I'm not sure that should go here.

**Comment by trotzig** [comment]
I started thinking about a way to add a comment to a js module to specify what it exports. What if you could do something like this:

```js
// @exports ['omit', 'debounce'] 
module.exports = {
 // ...
}
```

**Comment by lencioni** [comment]
It looks like `@exports` is already a thing in JSDoc, so it might not make the best syntax here. 

http://usejsdoc.org/tags-exports.html

**Comment by trotzig** [comment]
Good catch, we'll have to use something different. Though in general, what do you think of the approach?

**Comment by lencioni** [comment]
I think it might be okay. I like how it is close to the code, so it is less likely to drift than a sidecar file of some sort. It also works well for defining destructuring for modules that are not packages, since you don't need extra configuration somewhere else. 

I worry a little about how something like this will perform, since it would require reading the files in order to determine if they can be matched for the variable.

Also, there's a lot of overlap with #107 here.

**Comment by lencioni** [comment]
Also, if using ES2015 syntax for modules, we might not need any additional syntax since if a file exports multiple things, there would just be multiple export statements:

```js
export function foo() { ... }
export function bar() { ... }
```

**Comment by trotzig** [comment]
Yeah, performance is going to be a problem here if we go down the local comment/ES2015 track as laid out above. I've tried my hardest to avoid solutions that involve reading all modules into memory, caching them, and then operating on that set. I want new files to be available immediately, and removed files to be gone instantly. Let's at least try to come up with solutions that avoid introducing this cache.

**Comment by trotzig** [comment]
In an effort to keep things simple, how do you feel about doing the split (`aliases` becomes `aliases` and `destructure`) as part of this issue, and then we open a new one for auto-grabbing the destructures from a module?

**Comment by lencioni** [comment]
Yeah I think that's fine. I hadn't intended this to include auto-grabbing the destructures from a module, and I think that might possibly be covered adequately enough by #107.

**Comment by lencioni** [comment]
I updated the title of this issue to capture our latest plan of attack.

**Comment by lencioni** [comment]
I'm not entirely sure what your plan is for this, so I'm going to let you tackle it @trotzig.

**Comment by trotzig** [comment]
Yeah, I haven't thought too much about this yet. But a split (aliases +
destructure) shouldn't be too tricky.

**Comment by lencioni** [comment]
In the `destructure` hash, what should the keys represent?

**Comment by trotzig** [comment]
Good question. We could do the destructured name, e.g. `omit`. And then the
value is the package name (or import path?). That would make lookup super
simple, but would generate a lot of duplicate values (e.g. for underscore).
So maybe package name/import path is a better key (and the destructures as
an array). If we want to get fancy we can allow a glob pattern for the key
to be able to match even more things, but I don't know if that makes sense.

Alternatively, we could make `destructures` an array itself, with objects
that describe each package and its destructured props, e.g.

```json
"destructures": [
  {
    "import_path": "React",
    "destructures": ["PropTypes"]
  }
]
```

**Comment by lencioni** [comment]
> We could do the destructured name, e.g. `omit`. And then the value is the package name (or import path?). That would make lookup super simple, but would generate a lot of duplicate values (e.g. for underscore).

I don't think we should optimize for lookup in the config format, since we should be able to easily map to whatever format works best internally. e.g. if a flat hash of variable name to packages is fastest, we can create that from whatever configuration is supplied.

> So maybe package name/import path is a better key (and the destructures as an array).

Yeah, I think this makes sense. Regarding import path, should they always be relative to the location of `.importjs.json`, should they be relative to any of the lookup paths in the configuration, or something else?

> If we want to get fancy we can allow a glob pattern for the key to be able to match even more things, but I don't know if that makes sense.

I don't think I understand how that would work. Can you explain in a little more detail what you mean by this?

> Alternatively, we could make `destructures` an array itself, with objects that describe each package and its destructured props

What advantages do you see of this approach? It seems unnecessarily verbose to me, but I like that it is very clear what each value is and it would make it easier to add more configuration to this object in the future (although what would that be anyway?).

**Comment by trotzig** [comment]
>> If we want to get fancy we can allow a glob pattern for the key to be able to match even more things, but I don't know if that makes sense.

> I don't think I understand how that would work. Can you explain in a little more detail what you mean by this?

I'm just freestyling here, but what if you had modules under e.g. `app/helpers/**` that all exposed `{ escape, unescape }` or something. But that would be terrible for importing `escape`, since you have all the duplicates. I don't know what this was trying to solve tbh...

**Comment by trotzig** [comment]
>> Alternatively, we could make destructures an array itself, with objects that describe each package and its destructured props

> What advantages do you see of this approach? It seems unnecessarily verbose to me, but I like that it is very clear what each value is and it would make it easier to add more configuration to this object in the future (although what would that be anyway?).

Yep, that's what I thought. Instead of just having the key be the import path, we could give it a name, e.g. `"import_path": "react"`.

**Comment by trotzig** [comment]
> Regarding import path, should they always be relative to the location of .importjs.json, should they be relative to any of the lookup paths in the configuration, or something else?

I think it makes most sense if those were whatever import path would be used when importing the undestructured object, as if it would have been imported normally. So e.g. `react` (from `node_modules/react`, `lib/utils` (from `app/assets/lib/utils.js`).
