### ISSUE TITLE
Group imports into separate blocks

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#138]
It might be nice, perhaps as an option, to separate packages and local modules in the import block. What I mean by this is instead of having one import block that is all sorted alphabetically, import-js would manage two import blocks that are individually sorted alphabetically. The first would include any package dependencies, and the second would include any local dependencies.

Example:

```js
import _ from 'underscore';
import React from 'react';

import MyComponent from './MyComponent';
import SomeOtherThing from '../../SomeOtherThing';

// rest of file would go here
```

In files that have a lot of dependencies, this might help keep things a bit more organized and readable.

**Comment by trotzig** [comment]
I guess that would make sense. We could introduce a `sort` config option that by default is `alphabetic`. The above sorting could be e.g. `packages-first`. 

It might be tricky to update the `find_current_imports` method if we're adding space in between blocks. But it should be doable.

**Comment by trotzig** [comment]
I'm not working in any projects where this would be of much use, so I'm adding the `help wanted` label to allow others to contribute.

**Comment by lencioni** [comment]
Coupled with local configuration #108 and some of the extra local configuration needed for the custom import syntax issue #130, it would be nice if this would also create groups for any imports that use a different syntax.

**Comment by trotzig** [comment]
The more I think about this, the harder it seems. It's really hard to tell a package import apart from a file-import. Consider this example:

```js
import Abc from 'abc/abc';
import React from 'react';
import Foo from 'foo';
```

Let's say that we have a file called `foo.js` in the root. How do we tell that apart from `react`? The import paths don't hold enough information to make this useful (imo). 

However, we could implement block separation for imports using different import mechanisms. E.g.

```js
import Abc from 'abc/abc';
import React from 'react';

const bar = require('spec/bar');
const baz = require('spec/baz');
```

Though I'm not sure the benefits outweigh the cost. This is what would be produced by default:

```js
const bar = require('spec/bar');
const baz = require('spec/baz');
import Abc from 'abc/abc';
import React from 'react';
```
I feel like that's enough. Do you disagree? :)

**Comment by lencioni** [comment]
I think this is fine. This is really a nice to have for me and is certainly not necessary.

As for separating packages, that would likely have to happen at a higher level--when we still have access to the ruby classes, before we are operating on just strings.

**Comment by lencioni** [comment]
I had an idea for this. Instead of using some sort of heuristic to determine what goes in which group, and figuring out what order to put the groups in, we could make the groupings explicit in the configuration file. By default everything would be in group 0, and you could specify any subset of files to be in whatever group index you wanted.

**Comment by trotzig** [comment]
I'm making some prep work for this now in the group-imports branch: https://github.com/trotzig/import-js/tree/group-imports

I'm trying to understand your suggestion about making groupings explicit. Would this config be able to support it? 

```json
"group_imports": [
  "packages", 
  "app/components/**",
  "tests/**"
```
"packages" is a special keyword that will match anything defined in `package.json`. We could potentially use "node_modules" here too. I'm not sure. 

We'll have to use the import paths to figure this out, so if you are using relative imports we need to expand it before checking the glob pattern. And to figure out if it's a package being imported, we need to cross-check it with `package.json`.

**Comment by lencioni** [comment]
No, that won't work if you want multiple paths to be in the same group. I
was thinking we could use the current applies to/applies from config groups
to specify paths. The config objects would then also have a group index
config that y;u could optionally add (defaults to 0). Does that make sense?

**Comment by trotzig** [comment]
I see. That makes sense, though I'm mainly worried about how to deal with current imports here. I guess we could store information about what group a particular `ImportStatement` was in when it was parsed, and then reuse that. Though what do we do when this is in the file:

```js
import foo from 'foo';
import bar from 'bar';
```

Let's say that we now import something that is supposed to be in group 1. How do we know what group the two that are already there should end up in? We could look them up again I guess, though we're not guaranteed to get the right module back. And it's time-consuming to have to re-import every import again (I just did that for `rewrite_imports`, and I'd hate to do that all the time). 

I'm starting to think that the only practical thing to do here is to have a boolean config option, that when enabled will separate package dependencies, normal imports, and imports using `const`/`var`. I haven't really seen the need to group imports in my own projects so far, so I'm not sure if this is best for me to work on. It feels like I'm guessing a bit about the use-case... :)

**Comment by lencioni** [comment]
Since the to is based on the file being edited and the from is based on the
import path, it should be pretty easy to write a function that takes an
import and figures out the from that we would need to map it back to the
config file, right?

**Comment by trotzig** [comment]
The from is based on the path to the file/module, at import time. It's tricky to go from import path to file. Especially if you have multiple lookup paths and you're not using relative imports.

**Comment by lencioni** [comment]
Ah, that makes sense. So, I think you are right that the best way to do this is by determining groups based on heuristics. What do you think about the following groupings:

- `import ... from ...;`
  - packages
  - non-relative paths
  - relative paths
- `const ... = require(...);`
  - packages
  - non-relative paths
  - relative paths
- `var ... = require(...);`
  - packages
  - non-relative paths
  - relative paths
- custom require functions
  - packages
  - non-relative paths
  - relative paths

Which would result in something like the following:

```js
import Bar from 'bar';
import Foo from 'foo';
import { debounce } from 'underscore';

import AComponent from './AComponent';
import MyComponent from './MyComponent';
import SomethingElse from './SomethingElse';

import Utils from 'lib/utils';

const ThisIsAThingToo = myCustomRequireFunction('things/ThisIsAThingToo');
```

**Comment by lencioni** [comment]
Of course, it would more usually look something like this:

```js
import Bar from 'bar';
import Foo from 'foo';
import { debounce } from 'underscore';

import AComponent from './AComponent';
import MyComponent from './MyComponent';
import SomethingElse from './SomethingElse';
```

**Comment by trotzig** [comment]
👍👍👍

**Comment by lencioni** [comment]
I started a branch to work on this but ran out of time. Check it out if you like. https://github.com/trotzig/import-js/tree/groupings
