### ISSUE TITLE
goto function does not work when using aliases that result in relative paths

### ISSUE THREAD

**Issue by trotzig** [trotzig/import-js#142]
I have an object that is imported this way:

```js
const styles = require('./index.scss');
```

When using the goto function, the scss file won't open. 

I'm not 100% sure it's the relativeness, it could be because this is an alias as well.

**Comment by lencioni** [comment]
Goto seems to be working for me with relative paths, so I'd guess it is the alias in this case.

**Comment by trotzig** [comment]
Good to know.

**Comment by trotzig** [comment]
Changed the title to better reflect the issue.

**Comment by lencioni** [comment]
I think this was fixed by f93de0d443da32bbd61707b86449fe4ae6441766. If I am incorrect, please re-open.

**Comment by trotzig** [comment]
Correct.
