### ISSUE TITLE
Help people understand when they need to upgrade import-js

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#153]
If the format of the configuration file changes in a way that requires people to upgrade their editor plugins, it would be great if there was a built-in way to notify people that they need to do this.

I'm thinking that the simplest solution would be to add a line to the configuration file that says the minimum version of the plugin that is required. Then, when import-js runs, it can check its version against this value and if it isn't new enough, it can tell the person that they need to update their plugin.

Unfortunately, this doesn't work very well for the other direction, where the plugin is too new for the configuration version, but that seems less likely to cause major problems. If we wanted to solve for this, we could probably do something like semver ranges. I think this would probably work okay, but I worry that it would be unnecessarily confusing and cause too much churn in the configuration file.

Ideally, we'd figure out exactly how we want to solve this as soon as possible so it can start benefiting people as soon as the next release.

**Comment by trotzig** [comment]
> I'm thinking that the simplest solution would be to add a line to the configuration file that says the minimum version of the plugin that is required. Then, when import-js runs, it can check its version against this value and if it isn't new enough, it can tell the person that they need to update their plugin.

I think this is enough as a first pass. 

I had an idea that wouldn't require adding a version to the config file: 
If new and deleted configuration options we're tagged with the release they were added/removed in, then we could use that information to validate the current config. Oh, but wait -- that validation would happen on old code in some cases. And then we don't actually know what the new options are.

**Comment by lencioni** [comment]
What do you think this key should be named? What about `minimum_version`? Can you think of anything better?

**Comment by trotzig** [comment]
That sounds like a decent name.

**Comment by trotzig** [comment]
I'm about halfway through implementing this. I hope to push something soon.

**Comment by lencioni** [comment]
:100:

**Comment by trotzig** [comment]
How would you feel about allowing people to use e.g. `~> 1.2.3` here?

**Comment by lencioni** [comment]
I mentioned this in the original issue:

> Unfortunately, this doesn't work very well for the other direction, where the plugin is too new for the configuration version, but that seems less likely to cause major problems. If we wanted to solve for this, we could probably do something like semver ranges. I think this would probably work okay, but I worry that it would be unnecessarily confusing and cause too much churn in the configuration file.

If you want to go that route, go for it. But, we should use a different name than `minimum_version`.

**Comment by trotzig** [comment]
Ah, I didn't think about that mostly being useful in that direction. It was just that I came across this stdlib class: http://rubygems.rubyforge.org/rubygems-update/Gem/Dependency.html
