### ISSUE TITLE
Remove dependency on Ruby

### ISSUE THREAD

**Issue by wincent** [trotzig/import-js#17]
Depending on Ruby makes the plug-in harder to install (trust me, I know...) and the Ruby bit is actually pretty small, so it might be worth porting it to vimscript.

**Comment by lencioni** [comment]
I think this is a good suggestion, and would likely help this plugin be more popular.

@wincent what do you think are the best tools for testing vimscript? vimrunner? vader?

**Comment by wincent** [comment]
Yeah, I don't know too much about that. A while back I compiled a list of tools (https://wincent.com/wiki/Vim_testing_tools); there are six items on it and the options might have grown since then...

**Comment by trotzig** [comment]
One of the reasons that I wrote it in Ruby was because of this article that said this about unit-testing vim scripts:

> Unfortunately, unit testing Vim plugins lies somewhere between “painful” and “garden-weaseling your face” on the difficulty scale.

From: http://stevelosh.com/blog/2011/09/writing-vim-plugins/

Learning vim-script and garden-weaseling my face felt like too much at the time. ;)

Vimrunner looks promising to me at least. Then we can keep the rspec tests.

**Comment by wincent** [comment]
Also, I think it's fine to have Ruby as a development dependency, but if
you can avoid it as a runtime one that's a great advantage. I wish I could
do it in Command-T but it's the easiest way to package a C extension.

**Comment by trotzig** [comment]
I'm going to close this as a won't-fix. I currently don't have time or interest to invest in my vim-script skills. If people strongly disagree, I'm happy to re-open this issue and my mind to alternate programming languages. :)
