### ISSUE TITLE
Make import all work with eslint

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#18]
At Brigade we have recently switched from jshint/jsxhint to eslint, and it would be nice if this plugin worked with the eslint tool in the same way that it works with jshint/jsxhint.

**Comment by trotzig** [comment]
As a matter of fact, you can use `eslint` right now. If you add this configuration, it should work:

```json
    "jshint_cmd": "eslint --stdin --format compact" 
```

The name of that configuration option isn't great. Perhaps we should make a change to "find_undefined_variables_cmd"? And then make it compatible with anything that outputs a standard format (the "compact" format of `eslint` coincidentally (?) matches the output from jsx?hint. But there are other formatting options as well ("checkstyle" seems to be one of them).

**Comment by trotzig** [comment]
(The json formatting of the configuration is a commit in the making)

**Comment by lencioni** [comment]
Neat!

**Comment by trotzig** [comment]
Here's a commit to switch to eslint in the brigade repo: https://github.com/brigade/brigade/commit/d82748b026e43b38fadb74060736f5a4658cf66a

Unfortunately I have some issues pushing to our internal code review tool, so it'll live in that branch for a while.
