### ISSUE TITLE
imports were reordered, react was added on two lines

### ISSUE THREAD

**Issue by goatslacker** [trotzig/import-js#187]
Trying this out on vim and I had

```js
import Traps from 'traps';
import BoosterSeats from 'booster-seat-data';
import cx from 'classnames';
import CarMixin from '../../../components/CarMixin';

const PhotoCarousel = React.createClass({ ... });
```

I put my cursor under `React`, `leader-j`, and this happened to the imports.

```js
import BoosterSeats from 'booster-seat-data';
import CarMixin from '../../../components/CarMixin';
import React from
  'react';
import Traps from 'traps';
import cx from 'classnames';
```

* React is on two lines instead of one?
* The imports were re-ordered. While I normally don't have an issue with this convention, this can lead to noisy diffs. Also, it's a bit opinionated.

**Comment by lencioni** [comment]
Thanks for the issue report!

The extra line in the React import is pretty strange and definitely smells like a bug.

The ordering is intentional. I'd actually like to take it to the next level by adding configuration to define groups of imports: #138

**Comment by lencioni** [comment]
I just tried this out on the code you gave me and didn't run into the same problem. I bet this has something to do with our line length detection. @goatslacker what does `:set tw?` tell you? Will you try doing something like `:set tw=80` and run it again and see if you get a different result?

**Comment by lencioni** [comment]
I fired up a vim without any configuration with `vim -u NONE` and checked `:set tw?` and it seems to default to 0. We should probably use a default value in this case.

**Comment by lencioni** [comment]
We should probably also add a configuration option, since teams may want to wrap at the same point but people might not have similar editor configurations. We should maybe remove the editor configuration inspection for this altogether.

**Comment by lencioni** [comment]
@goatslacker I just merged a commit that I think will resolve your wrapping issue. Please reopen if it persists.

**Comment by trotzig** [comment]
Thanks for quickly dealing with this @lencioni. I agree that the re-ordering is opinionated @goatslacker and it will definitely lead to some noise in an early phase of introducing import-js to a codebase. In the long term however, I think it's useful to have consistent handling of all imports. @lencioni opened an issue a while ago describing a tool that might be helpful for you in order to do a one-pass over all files and "fix" (re-order, line-wrap, etc) imports: https://github.com/trotzig/import-js/issues/173

**Comment by goatslacker** [comment]
Works now as intended, thanks :)
