### ISSUE TITLE
Move max_line_length out of editor and back into configuration

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#189]
A long time ago, the max line length lived in configuration and I moved it to inspect Vim's configuration. As we add support for more editors, it will become increasingly difficult to support this type of inspection. Additionally, teams may use a wide variety of editors with a wide variety of configurations, but will probably want consistent line wrapping of their imports, so it makes more sense to put this in configuration.

See #187 for some more context.

**Comment by trotzig** [comment]
Makes sense. I have a feeling most will use the default anyway.

**Comment by trotzig** [comment]
Would it make sense to also move the `tab` config?

**Comment by lencioni** [comment]
I think so

**Comment by trotzig** [comment]
I'm working on this now
