### ISSUE TITLE
Add support for importing built in Node modules

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#201]
For instance, if you are writing code targeting Node.js, you might want to use a module that is part of the standard library, such as [`Path`](https://nodejs.org/dist/latest-v4.x/docs/api/path.html) or [`Net`](https://nodejs.org/dist/latest-v4.x/docs/api/net.html). When using something like this, you need to use `require('path')` first. It would be nice if import-js could be configured to resolve these for you.

I think it would probably make sense for these to be in their own group, sorted at the very top (above packages).

**Comment by lencioni** [comment]
It looks like [the Node.js documentation calls these core modules](https://nodejs.org/api/modules.html#modules_core_modules) and are all [defined in the `/lib` directory](https://github.com/nodejs/node/tree/master/lib).

Based on the files there, I believe this is a complete list:

```
assert
buffer
child_process
cluster
console
constants
crypto
dgram
dns
domain
events
fs
http
https
module
net
os
path
process
punycode
querystring
readline
repl
stream
string_decoder
sys
timers
tls
tty
url
util
v8
vm
zlib
```

**Comment by trotzig** [comment]
Until we have these built-in, it's easy to add them all to the `aliases` configuration if you want them now in a project.

**Comment by trotzig** [comment]
Okay, I'm about to implement this now. In terms of configuration option to turn this on, I have a few suggestions:

A) `project_type: 'node'`
B) `auto_import_node_core_modules: true`

A has the potential of being used for other purposes. But that might be premature. B feels a little long of a name, but it is quite obvious what it does.

What do you think @lencioni ?

**Comment by lencioni** [comment]
I don't like `project_type` since this may apply to just certain parts of a project.

It might be worth mimicking [how eslint does this](http://eslint.org/docs/user-guide/configuring#specifying-environments), by allowing people to specify which environments are being targeted. This would give us future flexibility while providing an API that people are likely familiar with:

```json
"env": {
  "node": true
}
```

**Comment by trotzig** [comment]
Interesting. I thought about this not always applying to the whole project as well. I like how `env` is generic enough. 

Funny thing - just the other day I was looking for a way to configure eslint the same way import-js is able to (by using the applies_to and applies_from patterns). I was left in the dark... I think I wanted to add globals for some parts of the codebase, but not apply it to the entire codebase.

**Comment by lencioni** [comment]
Yeah, unfortunately that is not possible with how eslint works (as far as I know). Which is one of the reasons I recommended the design we ended up with here.
