### ISSUE TITLE
Speed up ESLint runs by disabling as many rules that we don't need as possible

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#202]
Although there does not appear to be a way to tell ESLint to disable all rules except the ones you specify via CLI flags, we can disable all of the core rules manually using the `--rule` flag. I think that this might speed up ESLint runs a little.

I'm not entirely sure this is a good idea or if it is worth it, but it crossed my mind so I figured I'd open an issue.

**Comment by trotzig** [comment]
I think this makes sense. The external eslint call is the slowest part of importing at the moment.

**Comment by lencioni** [comment]
In my test, this either didn't make any difference, or it actually added a couple hundred ms. I timed the running of the command at about .65s on my machine and configuration. I think there may be some opportunities to make fixing imports faster, but I don't think this is one of them.

**Comment by trotzig** [comment]
I don't know if this is possible, but we could potentially keep an open eslint process running (waiting for stdin). This is assuming that startup time for eslint is significant (I'm not sure).

**Comment by lencioni** [comment]
What's weird is I had a dream where someone told me the same thing. I'm not sure eslint is designed for such a use case.

I think the biggest win we might see in this area would likely involve removing the ESLint dependency. One option is rewriting the plugin in node and then using a JS AST parser directly instead of depending on an external call to ESLint. Or perhaps we could get some of the benefit by implementing the specific checks that we are relying on ESLint for as a standalone Node package, in Ruby, a C extension.

**Comment by trotzig** [comment]
Are you sure you didn't just check your email notifications while semi-awake? ;)

Before going down the winding road of porting to js, it would be interesting to find out if there is a win to be made by using espree or something directly. I think so, but it would feel funny if we came to the conclusion that it didn't help after investing in all that Node.js juice.

**Comment by lencioni** [comment]
How do you think we should use espree directly?

**Comment by trotzig** [comment]
I meant use it after porting the project to Node.

**Comment by lencioni** [comment]
Oh right, that's precisely why I was thinking porting to Node would be better.

**Comment by trotzig** [comment]
I came across `eslint_d` just now. I'm trying it out locally for import-js and it does speed things up a bit. 

https://github.com/mantoni/eslint_d.js

**Comment by lencioni** [comment]
Oh that's right. I forgot about that project!

**Comment by ljharb** [comment]
Can you not do `eslint --no-eslintrc --rule X` or something similar?

**Comment by lencioni** [comment]
Unfortunately, we end up relying on other ESLint configuration for the project in order for everything to work properly.
