### ISSUE TITLE
Unused variables that share the names of imports confuse fix imports

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#203]
If you have code that looks something like the following:

```js
import uuid from 'uuid';

function bar() {
  return uuid.v4();
}

export default function foo() {
  const things = {
    uuid: bar(),
    henric: 'is cool',
  };

  const { uuid, henric } = things;
  return henric;
}
```

Running fix imports will toggle between adding and removing the `uuid` import. This is because the error that eslint reports relates to the `uuid` defined by `const { uuid, henric } = things;` line. However, after it is removed, we get a second error saying that it is used but never defined (by `return uuid.v4()`), so it gets added back again.

**Comment by trotzig** [comment]
Interesting find. I wonder if there's anything we can do about that without switching out eslint for a more direct integration with a parser?

**Comment by lencioni** [comment]
I think when eslint says that something is defined but not used, we can look at the line it reports and verify that it comes from an import statement.

**Comment by trotzig** [comment]
Oh, that's right. I was sort of blinded by the opposite case (adding the import).

**Comment by lencioni** [comment]
Yeah, the import is correctly added in this case, but incorrectly removed. :)
