### ISSUE TITLE
Issues with sublime 3 and rvm?

### ISSUE THREAD

**Issue by ljharb** [trotzig/import-js#219]
I tried to install the plugin in Sublime 3, but despite installing the import_js gem in my system ruby, and in all 3 of my rvm-installed rubies, I still get the message that it couldn't find the executable.

The popup suggests adding the path in my user settings - but there's no place under "Package Settings" for import-js, so I don't know where to add it, nor do I know the syntax/structure to add.

**Comment by trotzig** [comment]
To configure the path to the executable, you can follow these instructions (added in the [release notes for 0.2.1](https://github.com/trotzig/import-js/releases/tag/0.2.1)):

> Breaking change: The default Sublime setting for executable has changed to just import-js, from previously being ~/.rbenv/shims/import-js. If you were relying on the rbenv path, you need to override the executable setting with a full path to the import-js executable. Create or edit <path-to-sublime>/Packages/User/ImportJS.sublime-settings with something that looks like this:
```json
{
  "executable": "/Users/henrictrotzig/.rbenv/shims/import-js"
}
```
Please note that you can't use ~ to refer to the home directory, you need to specify the full path.

To figure out where rvm put the `import-js` executable, you can run `which import-js`.

Sorry for not having these in the Sublime docs. That's a mistake, and I'm going to follow up with a fix.

**Comment by lencioni** [comment]
There is also a popup that the sublime plugin generates that could probably be improved as well.

**Comment by lencioni** [comment]
I've improved some documentation, added a menu, and improved an error message, which I think will all help with this. Thanks for reporting it!

**Comment by ljharb** [comment]
thanks!

**Comment by lencioni** [comment]
@ljharb 0.6.0 is out now with these changes. Will you try it out and let us know if you have any more issues getting up and running?

**Comment by trotzig** [comment]
Package Control isn't great at finding new releases directly, so you might have to wait a while (assuming you use Package Control).

https://packagecontrol.io/packages/ImportJS

Still on 0.5.1.

**Comment by ljharb** [comment]
I am using Package Control - i'll let you know after it updates.

**Comment by trotzig** [comment]
Thanks!

**Comment by lencioni** [comment]
Looks like it has been updated!

**Comment by ljharb** [comment]
Thanks! One nit: i think the default user settings should be a copy of the default settings the first time they're opened (currently it's an empty file).

So - I updated, and set my executable to the system ruby's import-js path (`/usr/local/bin/import-js`), and now i get a popup with:
```
Error when executing import-js:

/usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/lib/import_js/importer.rb:190:in `run_eslint_command': env: node: No such file or directory (ImportJS::ParseError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/lib/import_js/importer.rb:78:in `fix_imports'
	from /usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/bin/import-js:66:in `<top (required)>'
	from /usr/local/bin/import-js:23:in `load'
	from /usr/local/bin/import-js:23:in `<main>'
```

I don't have a system node, I only have it installed via `nvm`. Do I need to tell it where node lives also?

**Comment by lencioni** [comment]
I don't think you should need to tell it anything about node. You probably need to configure the path to eslint. https://github.com/trotzig/import-js#eslint_executable

**Comment by lencioni** [comment]
You will also want to run `gem update import_js` to get on to 0.6.0.

**Comment by ljharb** [comment]
(I get the same thing on 0.6.0, fwiw)

**Comment by trotzig** [comment]
Just to make sure: did you also update the gem after uodating the plugin?
gem install import_sj

**Comment by lencioni** [comment]
I may be running into the same thing while working on the Atom plugin. In this case, I believe it is related to not setting up the env correctly before calling the external import-js command. Although I'm not sure why I don't see the same problem when running the Sublime plugin locally, so it may be different.
