### ISSUE TITLE
Add instructions of how to configure the Sublime plugin to SUBLIME.md

### ISSUE THREAD

**Issue by trotzig** [trotzig/import-js#220]
As discovered by @ljharb in https://github.com/trotzig/import-js/issues/219, there's no information how to configure the Sublime plugin in the Sublime docs. We need to inform people how to override the path to the executable, something like:

> If you get an error message saying something like "Can't find import-js executable", you may need to specify a path to the `import-js` executable in configuration. Create or edit /Packages/User/ImportJS.sublime-settings with something that looks like this:
```json
{
  "executable": "/Users/henrictrotzig/.rbenv/shims/import-js"
}
```
Please note that you can't use ~ to refer to the home directory, you need to specify the full path. 
To figure out where your `import-js` executable is located, you can run `which import-js`.

**Comment by lencioni** [comment]
It would be nice to have sections specifically detailing what to do if using rbenv and what to do if using rvm.
