### ISSUE TITLE
Match directories that have `index.js` or `index.jsx`

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#26]
If you have a component like `components/MyComponent/index.jsx`, you can `require` the directory (i.e. `require('components/MyComponent')` and it will default to the index. There is a table here that describes this behavior: http://webpack.github.io/docs/configuration.html#resolve-alias

It would be really great if import-js were able to match these directories.

**Comment by trotzig** [comment]
Fixed by https://github.com/trotzig/import-js/commit/8324f8c9fc20de2c72311c4e3e53deff37be787e
