### ISSUE TITLE
Allow configuration to leave file extensions intact

### ISSUE THREAD

**Issue by flarnie** [trotzig/import-js#29]
In some projects I prefer to configure webpack to not automagically add the file extension (`.js` or `.jsx`) to require statements, and then when using `import-js` I have to manually add it to the generated `require` statement.

We could add a configuration setting for 'include_file_extensions' that would allow `import-js` to leave the file extension as part of the `require` path.

**Comment by trotzig** [comment]
@flarnie: I just merged https://github.com/trotzig/import-js/commit/f05276b6014db36ca2aee21eeab7e800300618b9 that implements this. Let me know if it wasn't what you needed!
