### ISSUE TITLE
Enhancement: prevent finding nested dependencies

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#34]
If you are using import-js in a project that uses npm, you might have a folder structure that looks like:

```
node_modules/package/node_modules/something_else/node_modules/another_thing/utils.js
```

However, you should never `require` something that your app doesn't directly depend on, so it would be nice if anything in a nested `node_modules` directory was simply excluded from import-js.

Perhaps import-js should have a notion of excluded patterns and allow people to specify whatever fits their app? e.g.

```json
"exclude": [
  "node_modules/**/node_modules"
]
```

**Comment by trotzig** [comment]
This shouldn't be too hard to implement, and it makes sense. I'll give it a go soon.

**Comment by lencioni** [comment]
I woke up with perhaps a better solution in my mind, although I'm not sure if it will be any easier to implement or not. But instead of adding `exclude`, you could just make `include` accept glob patterns. So instead you could use:

```json
"lookup_paths": [
  "node_modules/*"
]
```

if you want just the top-level directory, or 

```json
"lookup_paths": [
  "path/to/nested/stuff/**/*"
]
```

if you want all directories. Although that's not **quite** as flexible as allowing excludes (since there might be other nested directories you **do** care about), it would probably be good enough.

If you end up adding an `exclude` option, you might want to either name it `exclude_lookup_paths` or rename `lookup_paths` to `include`, for symmetry (or use `include_lookup_paths` and `exclude_lookup_paths`).

**Comment by trotzig** [comment]
I was thinking of including this type of configuration in `lookup_paths` as well. But there are a few problems with that. Not only are `lookup_paths` places to look for files. It is also assumed that webpack/others know to look for modules in those directories. If we allowed glob patterns, what should we assume is the base directory in e.g. `node_modules/**/*`? 

My initial though to solving this problem would be to allow a lookup path to be either a string (as is now) or an object:

```json
'lookup_paths': [
  'app/assets',
  {
    'path': 'node_modules',
    'excludes': [
      '**/node_modules'
    ]
  } 
]
```

**Comment by lencioni** [comment]
> But I thought that would be overly complicated, and a single excludes configuration would probably be enough.

Agreed. I don't think the nested `excludes` really gives you any real advantages over having a separate `excludes` section. And actually, it might be a little confusing.
