### ISSUE TITLE
Feature request: add configuration to allow for automatic destructuring

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#38]
Let's say that you want to use a library that exports a single object that has a bunch of objects on it, but you want to just use those objects directly. It would be nice if import-js were able to be set up to allow for automatic destructuring.

For example, if I am using underscore, but instead of wanting to reference things like `_.memoize()` and `_.debounce()` I want to use `memoize()` and `debounce()`, it would be nice to be able to use import-js on the `memoize()` function call to grab the dependency like this:

```js
const { memoize } = require('underscore');
```

And if I trigger it again on another function call from the same package, it should add to the destructuring:

```js
const { debounce, memoize } = require('underscore');
```

**Comment by trotzig** [comment]
This is a good idea, but it might be hard to implement without having to make import-js actually execute javascript code (which I'm not sure is a good idea). For underscore, we would have to execute underscore.js and look at all methods assigned to `_`, such as `_.memoize`. 

Are there simpler ways of implementing this feature that you can think of?

**Comment by lencioni** [comment]
Could just require the destructured properties to be enumerated in config.

**Comment by trotzig** [comment]
That's a good idea. We could either add a ‘destructured_aliases‘ config
option or allow a single alias to be an object, e.g. ‘"memoize": { "path":
" underscore", "destructured": true }‘.

**Comment by lencioni** [comment]
I think it should be part of the aliases config, but it should be module-centric (like the example below), not property-centric (like the example you gave):

```json
"aliases": {
  "_": {
    "path": "underscore",
    "destructure": [
      "debounce",
      "memoize",
      "throttle"
    ]
  }
}
```

This has a couple of nice features: it allows the module itself to still be imported if you really want it, it is easy to add new properties to be destructured, and the shape of the configuration closely matches the structure of the object, which is good for mental models.

**Comment by trotzig** [comment]
:+1:
