### ISSUE TITLE
Extract core functionality into standalone program

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#47]
We have people on our team who use Vim, Emacs, and Sublime Text. It seems like each of these editors could benefit from this functionality, so it might be nice to extract the core of this plugin into a standalone program that individual plugins for each editor could then depend on.

**Comment by trotzig** [comment]
Interesting idea. The lock-in to VIM isn't particularly hard. I think an extraction would make testing slightly easier too. 

How do you suggest we go about doing this? Since there's no dependency management built into pathogen/vundler or vim plugins in general (or is there?). I guess we could release the core as a gem and then others would simply soft-depend on having that gem installed.

**Comment by lencioni** [comment]
> How do you suggest we go about doing this? Since there's no dependency management built into pathogen/vundler or vim plugins in general (or is there?). I guess we could release the core as a gem and then others would simply soft-depend on having that gem installed.

If you want to keep the core in Ruby, I think this makes sense.

**Comment by trotzig** [comment]
I thought about doing this in vim-script for a while but it just didn't seem worth it. I think I'll just turn this project into being able to publish a gem as well.

**Comment by lencioni** [comment]
> I thought about doing this in vim-script for a while but it just didn't seem worth it.

Agreed. I think there are two directions you can go with this:

1. Switch to entirely Vim script to make it easy for Vim users to adopt (since compiling Vim with Ruby support can be a big hurdle)
2. Extract core functionality into an external dependency to make it easy to add this functionality to other editors

I think the second one is more valuable. Plus, there might be a way to make Vim call external commands without using Ruby itself, which would possibly give you the first one as well while keeping most of the functionality in Ruby. That could likely be explored after first extracting.

**Comment by trotzig** [comment]
Since we now have our first non-VIM PR (emacs), I think we can close this issue. Thanks @lencioni for continuing to stress the importance of this!
