### ISSUE TITLE
ES2015 Modules

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#52]
It would be nice if import-js could be configured to produce `import` syntax used by ES2015 modules.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by trotzig** [comment]
:+1: I saw React-router and others are using that style of importing. Should (?) be simple I think.

**Comment by lencioni** [comment]
Here are some style guidelines used by the very popular Airbnb JS style guide that might be somewhat useful: https://github.com/airbnb/javascript#modules

**Comment by trotzig** [comment]
https://github.com/trotzig/import-js/commit/52d3e5851a509b3dff6102852d6cb3ac204dc8a0

**Comment by trotzig** [comment]
Closed through above referenced commit.
