### ISSUE TITLE
Delete unused imports on save

### ISSUE THREAD

**Issue by trotzig** [trotzig/import-js#60]
Wouldn't it be cool to configure your editor to run an import-cleanup task on save? Something that would find unused imports, and delete the ones not used. And potentially also import anything that's not been imported, but I can see that as a next step.

**Comment by lencioni** [comment]
I've also been thinking about running this on save, which should be about as easy as adding an `autocmd` right? #21 is probably a pre-requisite for this.

**Comment by trotzig** [comment]
I honestly thought this was my idea. And then it turns out @lencioni suggested it way back: #21 (not the part about doing it on save, but anyhow). lol :smile:

**Comment by lencioni** [comment]
> not the part about doing it on save

I don't mean to split hairs here, but I did suggest that in #21 :wink::

> With this feature, it might work really well to automatically run this when saving .js files with something like:

```vim
autocmd BufWritePre *.js :ImportJSAutoFix
```

> Then I could simply stop thinking about managing this bit of code in every file, freeing up my mind to think about more important things.

**Comment by trotzig** [comment]
Oh my, I need to stop imagining that I have own ideas! They're usually yours, my partners, or crazy.

**Comment by trotzig** [comment]
Closing, since this is really a duplicate of #21
