### ISSUE TITLE
Aliases with ".js*" in the end are stripped from file extension

### ISSUE THREAD

**Issue by trotzig** [trotzig/import-js#62]
I was in a situation where I needed to import `shared_config.json` (not `shared_config`). If I add `"SharedConfig": "shared_config.json"` to the `aliases` configuration, I still get this when I import:

```js
const SharedConfig = require('shared_config');
```

In this case the file ending is important (the import won't work withouth it).

**Comment by lencioni** [comment]
Since the [extensions that can be left out are configurable in e.g. webpack](https://github.com/webpack/docs/wiki/configuration#resolveextensions), this probably needs to be a configuration in import-js as well with the reasonable default of `.js`.
