### ISSUE TITLE
Rename to vim-import-js?

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#8]
Many Vim plugins are prefixed with `vim-`, which I think helps people find the plugins, understand what they are used for, and prevents naming collisions. I think it might be worth considering renaming this to `vim-import-js`, unless you plan on expanding it to support other editors, like Sublime. What do you think?

**Comment by trotzig** [comment]
Yeah, I've had the same thought. Will do when I have some time over.

**Comment by trotzig** [comment]
On second thought, I think I'll keep the name. Other vim plugins don't have the vim prefix (CommandT for instance) and I think it's fine to occupy that namespace for now. I'll reconsider when we get naming collisions with other editors.
