### ISSUE TITLE
Importing default and destructuring unnecessarily creates two separate imports when using import declaration keyword

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#83]
Currently, with `aliases` configuration like the following:

```json
"React": {
  "path": "react",
  "destructure": [
    "PropTypes"
  ]
}
```

importing both `React` and `PropTypes` will result in:

```js
import React from 'react';
import { PropTypes } from 'react';
```

but it would be better if it instead resulted in:

```js
import React, { PropTypes } from 'react';
```

I'm not sure if there is any equivalent syntax for CommonJS imports, but it would be really nice if ImportJS did this when using the `import` declaration keyword. I suppose if you were using CommonJS, it would be better to have one `require` and one assignment after the fact than two `require`s:

```js
const React = require('react');
const { PropTypes } = React;
```

**Comment by trotzig** [comment]
This is probably not super urgent, but I think it makes sense. It does introduce a bit of complexity keeping the two import variants apart, and getting the `const` case right might be tricky. Right now there are no dependencies amongst import statements, and introducing such will likely lead to some tricky complexity. I could see a first version where we treat the `import` variant separate in these cases.

**Comment by lencioni** [comment]
Yeah, I think it would be just fine to start by adding support for the `import` case and punting on the `const`/`let`/`var` case for now.
