### ISSUE TITLE
Does not understand line breaks

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#9]
If I have a section of `require`d modules at the top that looks like this:

```js
const MyModule = require('path/to/my_module');
const MyModuleThatHasALongName =
  require('path/to/my_module_that_has_a_long_name');
const SomeModule = require('path/to/some_module');
```

import-js gets confused when adding a new module to the list:

```js
const AnotherModule = require('path/to/another_module');
const MyModule = require('path/to/my_module');

const MyModuleThatHasALongName =
  require('path/to/my_module_that_has_a_long_name');
const SomeModule = require('path/to/some_module');
```

where I would expect:

```js
const AnotherModule = require('path/to/another_module');
const MyModule = require('path/to/my_module');
const MyModuleThatHasALongName =
  require('path/to/my_module_that_has_a_long_name');
const SomeModule = require('path/to/some_module');
```

It would be nice if import-js worked better with this format.

Bonus points would be specifying a character limit (defaulted to `80`) that it would try to stay within when importing new dependencies.

**Comment by trotzig** [comment]
I made a change to deal with line-breaks better. I didn't add anything for auto-linebreaking yet, but I might do that next. Check it out and let me know what you think @lencioni!

**Comment by lencioni** [comment]
:+1: :rabbit: :tophat:

**Comment by lencioni** [comment]
I think this is closed now. I'll open a new issue for the auto-breaking behavior.
