### ISSUE TITLE
Sublime components need to be in the plugin directory

### ISSUE THREAD

**Issue by kevinkehl** [trotzig/import-js#92]
...or maybe some other directory, as long as they are outside the root. The root directory is a little cluttered at the moment.

**Comment by trotzig** [comment]
The problem is that they need to be there for Package Control to pick them up. We could solve this by moving the Sublime plugin out into its own repo, but there are some nice benefits of keeping everything in the same repo: easier to test, no need to maintain multiple readmes, etc.

**Comment by kevinkehl** [comment]
That's unfortunate. Agreed, much better than having its own repo.
